# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eyeimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('img', models.ImageField(max_length=200, upload_to='static/img/eye_imgs/', verbose_name='待分析图片')),
            ],
            options={
                'verbose_name': '眼球图片',
                'verbose_name_plural': '眼球图片',
            },
        ),
    ]
