# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='output_av',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('img', models.ImageField(max_length=200, upload_to='static/img/output_av/', verbose_name='生成的av图片')),
            ],
            options={
                'verbose_name': '生成的av图片',
                'verbose_name_plural': '生成的av图片',
            },
        ),
        migrations.CreateModel(
            name='output_vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('img', models.ImageField(max_length=200, upload_to='static/img/output_vessel/', verbose_name='生成的vessel图片')),
            ],
            options={
                'verbose_name': '生成的vessel图片',
                'verbose_name_plural': '生成的vessel图片',
            },
        ),
    ]
