# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_img', '0002_output_av_output_vessel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eyeimg',
            options={'verbose_name': '待分析眼球图片', 'verbose_name_plural': '待分析眼球图片'},
        ),
        migrations.AlterField(
            model_name='eyeimg',
            name='img',
            field=models.ImageField(max_length=200, upload_to='eye_imgs/', verbose_name='待分析图片'),
        ),
        migrations.AlterField(
            model_name='output_av',
            name='img',
            field=models.ImageField(max_length=200, upload_to='output_av/', verbose_name='生成的av图片'),
        ),
        migrations.AlterField(
            model_name='output_vessel',
            name='img',
            field=models.ImageField(max_length=200, upload_to='output_vessel/', verbose_name='生成的vessel图片'),
        ),
    ]
