# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_img', '0003_auto_20190514_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_av',
            name='origin_img',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='display_img.Eyeimg', verbose_name='原图'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output_vessel',
            name='origin_img',
            field=models.ForeignKey(default='666', on_delete=django.db.models.deletion.CASCADE, to='display_img.Eyeimg', verbose_name='原图'),
            preserve_default=False,
        ),
    ]
